#!/bin/bash

CONTAINER_CONFIG_DIR="/etc/containerconf"
USER_CONTAINER_CONFIG_DIR="$CONTAINER_CONFIG_DIR/$USER"
CONTAINER_LIST_FILE="$CONTAINER_CONFIG_DIR/configs.d/.cherry/list.txt"
CONTAINER_OVERRIDE_CONFIG="$HOME/.config/containerconf.d/override.conf"
SUBMODULE_PATH="/usr/libexec/ostools"

help() {
  cat <<EOF 
Usage: cherry <subcommand> [option]

Subcommands:
  stem                        baseOS commands
  branch                      containerOS commands
  pesticide                   FSguard commands
  version                     show program version
  help                        show this dialogue
EOF
}

version() {
  echo "cherry v2.3.0"
}

case "$1" in
  stem)
    shift
    $SUBMODULE_PATH/baseos-submodule "$@"
    ;;
  branch)
    shift
    $SUBMODULE_PATH/containers-submodule "$@"
    ;;
  pesticide)
    shift
    $SUBMODULE_PATH/fsguard-submodule "$@"
    ;;
  version)
    version
    ;;
  help)
    help
    ;;
  *)
    help
    exit 1
    ;;
esac