#!/bin/bash

# THIS IS A SUBMODULE OF `cherry`, AND SHOULD NOT BE RUN DIRECTLY!!!

# set variables
FILENAME_TMP=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 35 ; echo '')
PS3="> "

# set help text
help() {
  cat <<EOF
Usage: cherry branch [option]

Options:
  grow                        create a new container
  snap <container_name>       remove an existing container
  cut <container_name>        save the specified container to an image
  attach <image_path>         load a container from an image
  jump <container_name>       switch to a different container
  list                        list all containers
  help                        show this dialogue
EOF
}

# main function
case "$1" in
    "grow")
        echo "Do you want to:"
        select container in "Choose from a list of images" "Specify your own (advanced)"; do
            if [[ -n $container ]]; then
                case "$container" in
                    "Choose from a list of images")
                        echo "Select an image from the list:"
                        select image in $(cat /etc/containerconf/.cherry/list.txt); do
                            if [[ -n $image ]]; then
                                distrobox-assemble create --file "/etc/containerconf/$image.ini"
                                echo "Done! You can switch to the container using 'cherry branch jump'."
                                break
                            else
                                echo "Invalid selection."
                                exit 1
                            fi
                        done
                        ;;
                    "Specify your own (advanced)")
                        read -p "Container URL/alias: " manual_container_url
                        read -p "Container name: " manual_container_name
                        echo "An editor will open to allow you to specify additional options."
                        echo "If you do not know how to specify additional options in the editor,"
                        echo "Please type the word help and press enter."
                        echo "When you're done looking at the help file, press q to exit."
                        echo "Then, reselect 'Specify your own (advanced)' to continue."
                        echo "If you don't need help, just press enter."
                        read -p "> " container_help_var
                        if [[ "$container_help_var" == "help" ]]; then
                            less /etc/containerconf/.cherry/editor-syntax.txt
                            new_container
                        else
                            cp /etc/containerconf/.ini-template "/tmp/$FILENAME_TMP.ini"
                            sed -i "s/<name>/$manual_container_name/g" "/tmp/$FILENAME_TMP.ini"
                            sed -i "s/<url>/$manual_container_url/g" "/tmp/$FILENAME_TMP.ini"
                            nano "/tmp/$FILENAME_TMP.ini"
                            distrobox-assemble create --file "/tmp/$FILENAME_TMP.ini"
                            rm "/tmp/$FILENAME_TMP.ini"
                        fi
                        echo "Done! You can switch to the container using 'cherry branch jump'."
                        exit 0
                        ;;
                    *)
                        echo "Invalid choice."
                        exit 1
                        ;;
                esac
            fi
        done
        ;;
    "snap")
        if [[ -z $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$') ]]; then
            echo "No containers to remove."
            exit 1
        else
            echo "Select a container by its number to remove it."
            select container in $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$'); do
                if [[ -n $container ]]; then
                    distrobox-rm "$container"
                    break
                else
                    echo "Invalid selection."
                    exit 1
                fi
            done
        fi
        ;;
    "cut")
        if [[ -z $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$') ]]; then
            echo "No containers to save."
            exit 1
        else
            echo "Select a container by its number to save it to an image."
            select container in $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$'); do
                if [[ -n $container ]]; then
                    podman save "$container" "$HOME/$container.tar"
                    echo "Container image saved at $HOME/$container.tar"
                    break
                else
                    echo "Invalid selection."
                    exit 1
                fi
            done
        fi
        ;;
    "attach")
        shift
        if [[ ! -f "$1" ]]; then
            echo "Error: Image path not found."
            exit 1
        fi
        podman load "$1"
        echo "Container loaded from $1. You can switch to it using 'cherry branch jump'."
        ;;
    "jump")
        if [[ -z $(distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$') ]]; then
            echo "No containers to switch to."
            exit 1
        else
            echo "Select a container by its number to switch to it."
            select container in $(distrobox-list | awk '{print $3}' | grep -v '^NAME$' | sed 's/^cherry-cli$/default container/'); do
                if [[ -n $container ]]; then
                    exec distrobox-enter "$container" -- bash
                else
                    echo "Invalid selection."
                    exit 1
                fi
            done
        fi
        ;;
    "list")
        distrobox-list | awk '{print $3}' | grep -v -e '^NAME$' -e '^cherry-cli$'
        ;;
    "help")
        help
        ;;
    *)
        echo "Error: Invalid option."
        help
        exit 1
        ;;
esac