#!/bin/bash

# THIS IS A SUBMODULE OF `cherry`, AND SHOULD NOT BE RUN DIRECTLY!!!

# set help text
help() {
  cat <<EOF
Usage: cherry pesticide [option]

Options:
  status                      show the status of enrolled directories
  check                       check the integrity of enrolled directories
  apply                       enroll a new directory
  help                        show this dialogue
EOF
}

# main function
case "$1" in
    status)
        /usr/libexec/pesticide/status
        ;;
    check)
        /usr/libexec/pesticide/check
        ;;
    apply)
        shift
        /usr/libexec/pesticide/enroll "$@"
        ;;
    help)
        help
        ;;
    *)
        help
        exit 1
        ;;
esac